name: Division Builds
description: Builds for the game Tom Clancy's The Division
author: Zerthox
icon: https://avatars.githubusercontent.com/u/28059051
google_analytics: UA-98254613-1

exclude:
    - README.md
    - Gemfile

sass:
    sass_dir: /
    style: compressed
plugins:
  - jekyll-sitemap